const theme=document.createElement("link");theme.rel="stylesheet";theme.href="neumorphism.css";document.head.appendChild(theme);const documentsScript=document.createElement("script");documentsScript.src="documents.js";documentsScript.defer=true;document.head.appendChild(documentsScript);
const courses={s1:[
{title:"Filosofi Pendidikan dan Pendidikan Nilai",connection:"Gagasan Ki Hadjar Dewantara menguatkan peran guru sebagai pamong yang menuntun potensi anak.",challenge:"Menggeser kebiasaan dari sekadar transfer pengetahuan menuju pendidikan nilai melalui keteladanan.",concept:"Kodrat alam dan zaman, sistem among, Pancasila, etika, dan kode etik profesi guru.",change:"Merancang pembelajaran yang memerdekakan, berkarakter, dan berpihak pada peserta didik."},
{title:"Peserta Didik dan Pemahamannya",connection:"Pemahaman perkembangan anak menjadi dasar untuk membaca keragaman kesiapan dan kebutuhan belajar.",challenge:"Satu pendekatan belum tentu sesuai bagi semua murid dengan profil belajar yang berbeda.",concept:"ZPD, perkembangan kognitif, ekologi perkembangan, diferensiasi, asesmen diagnostik, dan TaRL.",change:"Mengawali pembelajaran dengan asesmen diagnostik serta menyusun dukungan belajar terdiferensiasi."},
{title:"Pembelajaran Mendalam dan Asesmen Dasar",connection:"Perencanaan perlu menghubungkan tujuan, pengalaman belajar, dan bukti ketercapaian.",challenge:"Aktivitas yang ramai tidak selalu menunjukkan terjadinya proses berpikir mendalam.",concept:"Mindful, meaningful, joyful; Understanding by Design; asesmen autentik; memahami, mengaplikasi, merefleksi.",change:"Menggunakan asesmen formatif berkelanjutan dan umpan balik yang membantu murid bertumbuh."},
{title:"PPL Terbimbing",connection:"Teori tentang kebutuhan peserta didik diuji dalam situasi kelas yang nyata.",challenge:"Menjaga keterlibatan kelas sambil merespons perbedaan kemampuan dan gaya belajar.",concept:"Profiling peserta didik, media konkret, diferensiasi, kolaborasi, dan pengelolaan kelas.",change:"Memperkuat hands-on learning, pembagian peran kelompok, serta rutinitas kelas yang jelas."},
{title:"Pola Pikir Bertumbuh",connection:"Cara guru memberi respons memengaruhi keyakinan murid terhadap kemampuan belajarnya.",challenge:"Mengubah pujian berpusat pada bakat menjadi umpan balik berpusat pada proses.",concept:"Neuroplastisitas, power of yet, process praise, kerangka 3P, dan asesmen MAP.",change:"Menormalisasi kesalahan sebagai bagian dari belajar dan mendokumentasikan perkembangan proses."},
{title:"Bahasa Inggris untuk Guru SD",connection:"Bahasa dapat dipelajari secara alami melalui rutinitas, konteks, dan interaksi di kelas.",challenge:"Memberi dukungan agar murid berani berbicara dan menulis tanpa takut salah.",concept:"Classroom language, scaffolding, task-based learning, diferensiasi, dan asesmen autentik.",change:"Menggunakan lagu, permainan, media interaktif, serta scaffolding terstruktur."}
],s2:["Pembelajaran Sosial Emosional","Pembelajaran Mendalam dan Asesmen Lanjut","PPL Mandiri","Projek Kepemimpinan","Mata Kuliah Selektif/Elektif"].map(title=>({title,pending:true}))};
const grid=document.querySelector("#course-grid");function renderCourses(s){grid.innerHTML=courses[s].map((c,i)=>`<article class="course-card ${c.pending?'pending-card':''}"><button class="course-summary" type="button" aria-expanded="false"><span class="number">${String(i+1).padStart(2,'0')}</span><span><strong>${c.title}</strong><small>${c.pending?'Refleksi belum dilengkapi':'Buka refleksi 4C'}</small></span><span class="chevron">+</span></button><div class="course-body">${c.pending?'<p>Bagian disiapkan sesuai panduan, tetapi isi refleksi dan bukti dukung Semester II belum tersedia pada situs awal.</p>':`<div class="four-c"><div><b>Connection</b><p>${c.connection}</p></div><div><b>Challenge</b><p>${c.challenge}</p></div><div><b>Concept</b><p>${c.concept}</p></div><div><b>Change</b><p>${c.change}</p></div></div><p class="artifact"><strong>Artefak pendukung:</strong> tautan dokumen dan analisis bagian relevan perlu ditambahkan.</p>`}</div></article>`).join("");grid.querySelectorAll(".course-summary").forEach(b=>b.addEventListener("click",()=>{const c=b.closest(".course-card"),o=c.classList.toggle("open");b.setAttribute("aria-expanded",String(o))}))}document.querySelectorAll(".tab").forEach(t=>t.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(x=>{x.classList.toggle("active",x===t);x.setAttribute("aria-selected",String(x===t))});renderCourses(t.dataset.semester)}));renderCourses("s1");
const menu=document.querySelector(".menu-button"),nav=document.querySelector("#nav-list");menu.addEventListener("click",()=>{const o=nav.classList.toggle("open");menu.setAttribute("aria-expanded",String(o))});nav.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{nav.classList.remove("open");menu.setAttribute("aria-expanded","false")}));const ro=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");ro.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll(".reveal").forEach(e=>ro.observe(e));const ss=[...document.querySelectorAll("main section[id]")],ls=[...document.querySelectorAll(".nav-list a")];const spy=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)ls.forEach(a=>a.classList.toggle("active",a.getAttribute("href")==="#"+e.target.id))}),{rootMargin:"-40% 0px -52%"});ss.forEach(s=>spy.observe(s));
